[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/time"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.2"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.12.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.2"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "gopkg.in/fsnotify/fsnotify.v1"
