---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: natsclusters.nats.io
spec:
  group: nats.io
  names:
    kind: NatsCluster
    listKind: NatsClusterList
    plural: natsclusters
    singular: natscluster
    shortNames:
    - nats
  scope: Namespaced
  version: v1alpha2
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: natsserviceroles.nats.io
spec:
  group: nats.io
  names:
    kind: NatsServiceRole
    listKind: NatsServiceRoleList
    plural: natsserviceroles
    singular: natsservicerole
  scope: Namespaced
  version: v1alpha2
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nats-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nats-operator
  template:
    metadata:
      labels:
        name: nats-operator
    spec:
      serviceAccountName: nats-operator
      containers:
      - name: nats-operator
        image: connecteverything/nats-operator:0.3.0-v1alpha2
        imagePullPolicy: Always
        ports:
        - name: readyz
          containerPort: 8080
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        readinessProbe:
          httpGet:
            path: /readyz
            port: readyz
          initialDelaySeconds: 15
          timeoutSeconds: 3
