apiVersion: "nats.io/v1alpha2"
kind: "NatsCluster"
metadata:
  name: "nats-cluster"
spec:
  size: {{ .Values.clusterSize }}
  version: "1.3.0"

  pod:
    enableConfigReload: {{ .Values.configReload.enabled }}
    reloaderImage: {{ .Values.reloaderImage}}
    reloaderImageTag: {{ .Values.reloaderImageTag}}
    reloaderImagePullPolicy: {{ .Values.reloaderImagePullPolicy}}
  
  auth:
    enableServiceAccounts: {{ .Values.auth.enableServiceAccounts }}
    clientsAuthSecret: {{ template "nats.fullname" . }}-clients-auth
    clientsAuthTimeout: 5

  {{- if .Values.tls.enabled }}
  tls:
    # Certificates to secure the NATS client connections:
    serverSecret: {{ .Values.tls.serverSecret }}

    # Certificates to secure the routes.
    routesSecret: {{ .Values.tls.routesSecret }}
  {{- end }}
